Milestone 4: Add Basic User-Interface
carlylechia/School-Library pull request #4
Opened 2022-05-27 21:16 UTC by carlylechia

The goal of this milestone was to make the School-Library Application interactive. This was achieved by providing it with a basic UI, done in the following steps:

- [ ] Created an `app.rb` file that served as a console app entry-point. It has methods that do the following:

  - List all books.
  - List all people.
  - Create a person (teacher or student, not a plain Person).
  - Create a book.
  - Create a rental.
  - List all rentals for a given person's id.

- [ ] In the `main.rb` file, the entry point was defined, which is a method called **main** that is invoked at the end of the file. This method does the following:

  - Presents the user with a list of options to perform.
  - Lets users choose an option.
  - If needed, asks for parameters for the option.
  - Has a way to quit the app.

2022-05-27 22:04 UTC, andersonlebon requested changes
## Hi @carlylechia 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 22:04 UTC, andersonlebon commented on app.rb
> +  end
- [ ] Kindly solve this error when trying to list all rentals. :point_down: 

![image](https://user-images.githubusercontent.com/65068771/170794678-06a9ae13-a0b3-4b97-ba7b-68a259d7d04b.png)

2022-05-27 22:07 UTC, carlylechia commented on app.rb
> +  end
Thank you @andersonlebon. Working on it
Do you have any pointers on what I can do to fix that particular issue, please?

2022-05-27 23:56 UTC, Lordkaito requested changes
Hi @carlylechia, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 23:56 UTC, Lordkaito commented on app.rb
> +class App
- [ ] Good job applying some changes to what the previous reviewer asked, but it seems that you are still missing something. Here's an image of the actual behavior of your app:
![Captura de pantalla 2022-05-28 015253](https://user-images.githubusercontent.com/59100477/170801162-49a05384-55d1-4866-b9f9-237fb95ceda8.jpg)

If you take a close look, you will see that I was able to create a person, a book, and theoretically also a rental. Whenever I press 1, I see all books, when I press 2, I see all people, but whenever I press 6 and select the person I want to see the rentals from, it is showing nothing. Probably you are not showing the right content, or maybe you missed something there, so please try to fix that.

2022-05-28 18:27 UTC, medaminedev66 requested changes
Hi @carlylechia 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Option 6 (List all the rentals for a given person's id) works as expected. Great job 👍.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 18:27 UTC, medaminedev66 commented on app.rb
> +  end
- [ ] I tried to create a student in your app, but received the following error message:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/77190203/170838048-7b22321f-b8f3-4fe7-addd-f93bf4109346.png">

- Please make sure that the console app works as expected. (The user should be able to create students).

2022-05-28 18:36 UTC, carlylechia commented on app.rb
> +  end
@andersonlebon There must be a mixup somewhere because the app works perfectly here on my PC in creating students and performing every other task

2022-05-28 19:02 UTC, carlylechia commented on app.rb
> +  end
> * [ ]  I tried to create a student in your app, but received the following error message:
> 
> <img alt="image" width="622" src="https://user-images.githubusercontent.com/77190203/170838048-7b22321f-b8f3-4fe7-addd-f93bf4109346.png">
> 
> * Please make sure that the console app works as expected. (The user should be able to create students).

Please can you cross-check the UI again and reply to me?

2022-05-28 20:03 UTC, bimbolabuari approved these changes
Hi @carlylechia, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 20:06 UTC, merged

2022-05-30 12:27 UTC, medaminedev66 commented on app.rb
> +  end
> There must be a mixup somewhere because the app works perfectly here on my PC in creating students and performing every other task...

Hi @carlylechia, 
It's weird. This issue still shows up on my source-code editor after creating a student. I tested your app on another editor and it worked perfectly. It's possible that this problem is caused by the Ruby version.